apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-volume
  labels:
    directory: etc
spec:
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - port=2049
    - proto=tcp
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.178.3
    path: "/Cluster/pihole/etc"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-volume
  labels:
    directory: dnsmasq.d
spec:
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - port=2049
    - proto=tcp
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.178.3
    path: "/Cluster/pihole/dnsmasq.d"
