apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  # the upstream nameserver is the pihole DNS server running in this cluster
  # $ kubectl -n services get services pihole -o jsonpath='{.spec.externalIPs[0]}'
  # 192.168.178.90
  upstreamNameservers: |
    ["192.168.178.90"]
