apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: ddns-update
  name: ddns-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddns-update
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ddns-update
    spec:
      restartPolicy: Always
      containers:
      - name: tiny-godaddy-ddns
        image: alcol/tiny-godaddy-ddns:latest
        env:
        - name: FREQUENCY
          value: "5"   # minutes
        - name: DOMAIN
          value: "example.com"
        - name: TYPE
          value: "A"
        - name: NAME
          value: "@"
        - name: TTL
          value: "1800" # seconds
        - name: PORT
          value: "1"
        - name: WEIGHT
          value: "1"
        - name: KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: godaddy-api
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: godaddy-api
